insert INTO category (categoryId, categoryName) VALUES
(1, 'Clothing'),
(2, 'Electronics'),
(3, 'Appliances'),
(4, 'Grocery'),
(5, 'Toys');
MERGE INTO product (id, name, brand, price, imageurl, rating, category_id) VALUES
(1, 'Wide Bowknot Hat', 'MAJIK', 288, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-cap.png', 3.6, 1),
(2, 'Plain Round Neck T-shirt', 'Huetrap', 395, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-fit-t-shirt.png', 4.1, 1),
(3, 'Cotton Hoodie', 'Scott International', 498, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-hoodie.png', 3.8, 1),
(4, 'Mens Waistcoat', 'LEVIS', 2500, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-jacket.png', 4.3, 1),
(5, 'Slim Fit Jeans', 'LEVIS', 1469, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-jeans-pants.png', 3.1, 1),
(6, 'Miss Chase Bodycon Dress', 'LEVIS', 974, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-modren-net.png', 3.8, 1),
(7, 'Zari Design Kurta', 'Libas', 1869, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-punjabi.png', 4.4, 1),
(8, 'Slim Fit Blazer', 'LEVIS', 2599, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-purple-jacket.png', 4.2, 1),
(9, 'Animal Printed Shirt', 'Mufti', 1017, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-short-sleeves-shirt.png', 4, 1),
(10, 'Polyester Saree', 'Ahalyaa', 419, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-side-sareee.png', 3.8, 1),
(11, 'Warm Up Jacket', 'Monte Carlo', 2796, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-sim-jacket.png', 4.4, 1),
(12, 'Wrap Dress', 'Vero Moda', 3039, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-simple-formal.png', 3.2, 1),
(13, 'Knit Cream Sweater', 'MansiCollections', 996, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-stylish-sweater.png', 3.2, 1),
(14, 'Sheer Anarkali', 'Saadgi', 2172, 'https://assets.ccbp.in/frontend/react-js/ecommerce/clothes-white-punjabi.png', 3.2, 1),
(15, 'Embellished Maxi Dress', 'STREET 9', 1799, 'https://assets.ccbp.in/frontend/react-js/ecommerce/cloths-blue-fork.png', 3.2, 1),
(16, 'Embroidered Net Gown', 'Manyavar', 62990, 'https://assets.ccbp.in/frontend/react-js/ecommerce/cloths-long-fork.png', 3.2, 1),
(17, 'Analog Mens Watch', 'Fastrack', 1850, 'https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-casual-watch.png', 4.2, 2),
(18, 'Tea Kettle Pot', 'Indian Art Villa', 1685, 'https://assets.ccbp.in/frontend/react-js/ecommerce/electronics-copper-kettle.png', 3.8, 2),
(19, 'Handheld Full Body Massager', 'AGARO REGAL', 1299, 'https://assets.ccbp.in/frontend/react-js/ecommerce/appliances-body-massager.png', 4.3, 3),
(20, 'True Wireless Earbuds', 'LG', 13499, 'https://assets.ccbp.in/frontend/react-js/ecommerce/appliances-ear-buds.png', 4.4, 3),
(21, 'Mixer Grinder', 'Lifelong', 1699, 'https://assets.ccbp.in/frontend/react-js/ecommerce/appliances-mixer-grinder.png', 3.9, 3),
(22, 'SilverBullet Mixer Grinder', 'COOKWELL', 1899, 'https://assets.ccbp.in/frontend/react-js/ecommerce/appliances-mixer-grinder-white.png', 4.1, 3),
(23, 'PS5 Controller Charger', 'New World', 1749, 'https://assets.ccbp.in/frontend/react-js/ecommerce/appliances-ps5-controller.png', 3.3, 3),
(24, 'Podcast Microphone', 'MAONO', 5555, 'https://assets.ccbp.in/frontend/react-js/ecommerce/appliances-singing-mike.png', 4.4, 3),
(25, 'Dynamic Microphone', 'JTS Store', 1699, 'https://assets.ccbp.in/frontend/react-js/ecommerce/appliances-solo-mike.png', 3.9, 3),
(26, 'Front Load Machine', 'Samsung', 22490, 'https://assets.ccbp.in/frontend/react-js/ecommerce/appliances-washing-machine.png', 4.5, 3),
(27, 'Eggs', 'Naturoz', 60, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery-eggs.png', 3.6, 4),
(28, 'Chilli Extract Sauce', 'Everin', 788, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery-extract.png', 4.1, 4),
(29, 'Flour Unbleached', 'TWF Store', 200, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery--flour.png', 4.3, 4),
(30, 'Fresh Produce Green Chilli', 'Amazon', 30, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery-green-chilli.png', 4.2, 4),
(31, 'Maroon Kumkum', 'Amazon', 200, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery--kumkum.png', 3.9, 4),
(32, 'Fresh Lemon, 100g', 'Amazon', 50, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery-lemons.png', 4.5, 4),
(33, 'Virgin Avocado Oil', 'ProV', 4144, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery-oil.png', 4.4, 4),
(34, 'Basmati Rice', 'Fortune', 244, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery-rice.png', 3.6, 4),
(35, 'Crystal Sugar', 'NatureVit', 278, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery-sugar-cubes.png', 3.6, 4),
(36, 'Turmeric Powder', 'Patanjali', 1234, 'https://assets.ccbp.in/frontend/react-js/ecommerce/grocery-turmeric.png', 2.8, 4),
(37, 'Batman Batmobile', 'Funskool', 745, 'https://assets.ccbp.in/frontend/react-js/ecommerce/toys-batman-toy.png', 4.7, 5),
(38, 'Captain America Shield', 'Funskool', 1450, 'https://assets.ccbp.in/frontend/react-js/ecommerce/toys-captain-america-shield.png', 4.5, 5),
(39, 'Iron Man Shield', 'Funskool', 850, 'https://assets.ccbp.in/frontend/react-js/ecommerce/toys-iron-man-shield.png', 4.1, 5),
(40, 'Spider-Man Car', 'Funskool', 1100, 'https://assets.ccbp.in/frontend/react-js/ecommerce/toys-spiderman-car.png', 3.9, 5),
(41, 'Transformers Bot', 'Hasbro', 2900, 'https://assets.ccbp.in/frontend/react-js/ecommerce/toys-transformer-bot.png', 4.4, 5);